"""add user_id to meetings

Revision ID: 3c8f5e77a6ec
Revises: 90992463b6af
Create Date: 2026-08-29 22:22:23.561375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8f5e77a6ec'
down_revision: Union[str, Sequence[str], None] = '90992463b6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'meetings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_column('meetings', 'user_id')
    # ### end Alembic commands ###
